### ISSUE TITLE
"Univerity" Typo

### ISSUE THREAD

**Issue by abrad45** [benjamintd/codegame.cards#69]
I played a game today and saw "Univerity" as a clue. It looks like that typo was fixed in https://github.com/benjamintd/codegame.cards/blob/master/lib/dictionary-en.ts some time ago.

How recently was this code pushed to the `codegame.cards` site?

**Comment by benjamintd** [comment]
I think this should be fixed? Closing until someone finds that word in a game again 🤷‍♂️. Sorry about that!
